# Community package requirements: sanity tests and repository management

(Note: This issue was filed in a semi-automated fashion on behalf of the Ansible Community Steering Committee. Let me know if you see errors in this issue.)

As per the [Ansible community package inclusion requirements][ci-testing], collections must pass `ansible-test sanity` tests. Version `5.2.3` of `check_point.mgmt`, corresponding to the `v5.2.3` tag in this repo, fails one or more of the required sanity tests.

The contents in the `v5.2.3` git tag do not match `check_point-mgmt-5.2.3.tar.gz` as uploaded to Ansible Galaxy. For future releases, please make sure that the contents uploaded to Galaxy match the sources that were tagged as that release. See the [Repository management requirements][repo-mgmt] for more information.

Please see the errors below and address them. If these issues aren't addressed within a reasonable time period, the collection may be subject to [removal from Ansible][removal].

*Please fix the issues identified below and then create a new Galaxy release so the fixes are caught in the next round of automated testing.*

Thank you for your efforts and for being part of the Ansible package! We appreciate it.

---

## Sanity tests

The following tests were run using `ansible-test` version `2.17.3`:

- ansible-doc
- compile
- validate-modules
- yamllint

Note that this is only a subset of the required sanity tests. Please make sure you run them in all in your CI.

### Results

> **ðŸ’¡ NOTE:**
>
> Check the `[explain]` links below for more information about each test and how to fix failures.
> See [Sanity Tests: Ignores](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html) in the dev guide if, after reading the test-specific documentation, you still believe an error is a false positive.

The test `ansible-test sanity --test validate-modules` [[explain](https://docs.ansible.com/ansible-core/2.17/dev_guide/testing/sanity/validate-modules.html)] failed with 261 errors:

``` text
plugins/modules/cp_mgmt_abort_get_interfaces.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_layer.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_layer_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_point_name.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_point_name_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_role.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_role_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_rule.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_rule_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_rules.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_access_section.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_add_api_key.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_add_central_license.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_add_data_center_object.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_add_domain.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_add_nat_rule.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_add_repository_package.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_add_rules_batch.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_add_updatable_object.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_address_range.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_address_range_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_administrator.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_administrator_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_application_site.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_application_site_category.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_application_site_category_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_application_site_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_application_site_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_application_site_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_approve_session.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_assign_global_assignment.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_central_license_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_check_network_feed.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_check_threat_ioc_feed.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_checkpoint_host.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_checkpoint_host_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_cluster_members_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_connect_cloud_services.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_data_center_object_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_delete_api_key.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_delete_central_license.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_delete_data_center_object.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_delete_domain.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_delete_nat_rule.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_delete_repository_package.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_delete_rules_batch.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_delete_updatable_object.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_discard.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_disconnect_cloud_services.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_distribute_cloud_licenses.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_dns_domain.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_dns_domain_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_domain_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_domain_permissions_profile.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_domain_permissions_profile_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_dynamic_global_network_object.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_dynamic_global_network_object_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_dynamic_object.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_dynamic_object_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_exception_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_exception_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_export_management.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_export_smart_task.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_get_attachment.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_get_interfaces.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_get_platform.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_global_assignment.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_global_assignment_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_group_with_exclusion.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_group_with_exclusion_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_gsn_handover_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_gsn_handover_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_ha_full_sync.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_host.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_host_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_https_layer.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_https_layer_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_https_section.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_identity_tag.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_identity_tag_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_idp_administrator_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_idp_administrator_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_idp_to_domain_assignment_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_import_management.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_import_smart_task.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_install_database.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_install_lsm_policy.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_install_lsm_settings.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_install_policy.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_install_software_package.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_interoperable_device.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_interoperable_device_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_ips_protection_extended_attribute_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lock_object.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsm_cluster.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsm_cluster_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsm_cluster_profile_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsm_gateway.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsm_gateway_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsm_gateway_profile_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsm_run_script.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsv_profile.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_lsv_profile_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_md_permissions_profile.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_md_permissions_profile_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_mds.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_mds_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_multicast_address_range.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_multicast_address_range_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_nat_rule.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_nat_rule_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_nat_section.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_network.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_network_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_network_feed.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_network_feed_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_objects_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_package.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_package_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_provisioning_profile_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_publish.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_put_file.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_radius_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_radius_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_radius_server.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_radius_server_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_reject_session.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_repository_package_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_repository_script.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_repository_script_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_reset_sic.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_run_ips_update.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_run_script.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_security_zone.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_security_zone_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_citrix_tcp.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_citrix_tcp_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_compound_tcp.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_compound_tcp_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_dce_rpc.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_dce_rpc_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_icmp.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_icmp6.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_icmp6_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_icmp_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_other.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_other_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_rpc.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_rpc_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_sctp.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_sctp_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_tcp.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_tcp_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_udp.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_service_udp_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_session_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_api_settings.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_cloud_services.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_domain.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_global_domain.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_global_properties.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_ha_state.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_idp_default_assignment.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_idp_to_domain_assignment.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_ips_update_schedule.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_login_message.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_nat_rule.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_policy_settings.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_session.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_threat_advanced_settings.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_set_vpn_community_remote_access.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_access_section.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_api_settings.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_api_versions.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_azure_ad_content.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_changes.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_cloud_licenses_usage.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_cloud_services.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_commands.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_gateways_and_servers.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_global_domain.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_global_properties.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_ha_state.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_ha_status.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_https_section.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_idp_default_assignment.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_ips_status.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_ips_update_schedule.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_layer_structure.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_login_message.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_logs.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_nat_section.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_place_holder.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_policy_settings.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_servers_and_processes.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_software_package_details.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_software_packages_per_targets.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_task.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_tasks.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_threat_advanced_settings.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_unused_objects.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_updatable_objects_repository_content.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_show_validations.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_simple_cluster.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_simple_cluster_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_simple_gateway.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_simple_gateway_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_smart_task.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_smart_task_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_smart_task_trigger_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_smtp_server.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_smtp_server_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_submit_session.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_tacacs_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_tacacs_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_tacacs_server.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_tacacs_server_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_tag.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_tag_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_task_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_test_sic_status.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_exception.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_exception_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_indicator.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_indicator_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_layer.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_layer_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_profile.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_profile_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_protection_override.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_rule.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_threat_rule_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_time.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_time_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_time_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_time_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_trusted_client.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_trusted_client_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_uninstall_software_package.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_unlock_administrator.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_unlock_object.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_updatable_object_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_update_provisioned_satellites.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_update_updatable_objects_repository_content.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_user_group.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_user_group_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_verify_policy.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_verify_software_package.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_vpn_community_meshed.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_vpn_community_meshed_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_vpn_community_remote_access_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_vpn_community_star.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_vpn_community_star_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_vsx_run_operation.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_where_used.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_wildcard.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
plugins/modules/cp_mgmt_wildcard_facts.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'CertificateError' from 'ansible.module_utils.urls' (/root/ansible/lib/ansible/module_utils/urls.py)'
```



## File divergences

The following files differ between the `v5.2.3` git tag and `check_point-mgmt-5.2.3.tar.gz` on Ansible Galaxy:

- `plugins/module_utils/checkpoint.py` (`WRONG_HASH`)
- `changelogs/.plugin-cache.yaml` (`WRONG_HASH`)
- `changelogs/changelog.yaml` (`WRONG_HASH`)
- `CHANGELOG.rst` (`WRONG_HASH`)


[ci-testing]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#ci-testing
[repo-mgmt]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#repository-management
[removal]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst
