collections:
  awx.awx:
  - error: WRONG_HASH
    file: README.md
  check_point.mgmt:
  - error: WRONG_HASH
    file: tests/units/plugins/httpapi/test_checkpoint.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_wildcard.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_administrator_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_publish.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_global_assignment.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_dns_domain.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_assign_global_assignment.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_application_site_group.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_host_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_verify_software_package.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_security_zone_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_uninstall_software_package.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_group_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_application_site_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_checkpoint_host.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_profile_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_application_site.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_access_layer.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_icmp_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_vpn_community_star.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_indicator.py
  - error: WRONG_HASH
    file: tests/units/modules/test_checkpoint_task_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_udp.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_session_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_icmp6.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_access_role_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_add_data_center_object.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_show_https_section.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_simple_gateway_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_sctp_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_rule_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_group.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_host.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_access_layer_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_mds_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_application_site_group_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_rpc.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_network.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_vpn_community_meshed_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_discard.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_network_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_dce_rpc.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_delete_nat_rule.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_nat_section.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_simple_gateway.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_udp_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_icmp.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_exception_group.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_https_section.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_global_assignment_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_delete_api_key.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_time.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_multicast_address_range_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_other_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_checkpoint_access_rule.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_time_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_run_script.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_exception.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_delete_data_center_object.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_access_role.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_other.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_rpc_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_vpn_community_meshed.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_group_with_exclusion.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_group_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_group_with_exclusion_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_set_nat_rule.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_vpn_community_star_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_show_access_section.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_icmp6_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_layer_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_show_nat_section.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_dce_rpc_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_show_software_package_details.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_access_section.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_address_range.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_add_nat_rule.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_tag.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_put_file.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_dns_domain_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_indicator_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_address_range_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_tcp_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_exception_group_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_package.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_rule.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_data_center_object_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_dynamic_object_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_security_zone.py
  - error: WRONG_HASH
    file: tests/units/modules/test_checkpoint_session.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_multicast_address_range.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_tag_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_profile.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_wildcard_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_application_site_category.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_administrator.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_package_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_application_site_category_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_layer.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_install_policy.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_access_rule.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_run_ips_update.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_protection_override.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_access_rule_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_tcp.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_threat_exception_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_dynamic_object.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_verify_policy.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_install_software_package.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_add_api_key.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_nat_rule_facts.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_service_sctp.py
  - error: WRONG_HASH
    file: tests/units/modules/test_cp_mgmt_group.py
  - error: WRONG_HASH
    file: plugins/action/cp_mgmt_hosts.py
  - error: WRONG_HASH
    file: plugins/action/cp_mgmt_access_rules.py
  - error: WRONG_HASH
    file: plugins/doc_fragments/checkpoint_commands.py
  - error: WRONG_HASH
    file: plugins/doc_fragments/checkpoint_objects_action_module.py
  - error: WRONG_HASH
    file: plugins/doc_fragments/checkpoint_objects.py
  - error: WRONG_HASH
    file: plugins/doc_fragments/checkpoint_facts.py
  - error: WRONG_HASH
    file: plugins/httpapi/checkpoint.py
  cisco.ise:
  - error: WRONG_HASH
    file: playbooks/active_directory.yml
  cisco.meraki:
  - error: WRONG_HASH
    file: plugins/action/networks.py
  - error: WRONG_HASH
    file: plugins/plugin_utils/meraki.py
  - error: WRONG_HASH
    file: playbooks/networks.yml
  ibm.spectrum_virtualize:
  - error: WRONG_HASH
    file: playbooks/volume_migration_on_svc_iscsi/vol_migration_vars.txt
  - error: WRONG_HASH
    file: playbooks/multi_volume_create_host_mapping_zone_multipath/multiple_vol_creation_zone_map_vars.txt
  - error: WRONG_HASH
    file: README.md
  lowlydba.sqlserver:
  - error: WRONG_HASH
    file: .github/workflows/ansible-test.yml
  - error: WRONG_HASH
    file: .github/workflows/ansible-test-windows.yml
  ovirt.ovirt:
  - error: WRONG_GALAXY_YML_NAME
    file: galaxy.yml
    message: '`@NAMESPACE@.@NAME@` != `ovirt.ovirt`'
  - error: WRONG_HASH
    file: build.sh
  - error: WRONG_HASH
    file: CHANGELOG.rst
  - error: WRONG_HASH
    file: examples/filters/ovirtdiff.yml
  - error: WRONG_HASH
    file: examples/filters/vmips.yml
  - error: WRONG_HASH
    file: examples/ovirt_ansible_collections.yml
  - error: WRONG_HASH
    file: README.md
  - error: WRONG_HASH
    file: roles/repositories/examples/ovirt_repositories_release_rpm.yml
  - error: WRONG_HASH
    file: roles/repositories/examples/ovirt_repositories_subscription_manager.yml
  - error: WRONG_HASH
    file: roles/repositories/README.md
  - error: WRONG_HASH
    file: roles/cluster_upgrade/examples/cluster_upgrade.yml
  - error: WRONG_HASH
    file: roles/cluster_upgrade/README.md
  - error: WRONG_HASH
    file: roles/shutdown_env/examples/shutdown_env.yml
  - error: WRONG_HASH
    file: roles/shutdown_env/README.md
  - error: WRONG_HASH
    file: roles/disaster_recovery/examples/dr_ovirt_setup.yml
  - error: WRONG_HASH
    file: roles/disaster_recovery/examples/dr_play.yml
  - error: WRONG_HASH
    file: roles/disaster_recovery/README.md
  - error: WRONG_HASH
    file: roles/vm_infra/tasks/create_inventory.yml
  - error: WRONG_HASH
    file: roles/vm_infra/tasks/main.yml
  - error: WRONG_HASH
    file: roles/vm_infra/tasks/vm_state_present.yml
  - error: WRONG_HASH
    file: roles/vm_infra/examples/ovirt_vm_infra_inv.yml
  - error: WRONG_HASH
    file: roles/vm_infra/examples/ovirt_vm_infra.yml
  - error: WRONG_HASH
    file: roles/vm_infra/README.md
  - error: WRONG_HASH
    file: roles/image_template/tasks/qcow2_image.yml
  - error: WRONG_HASH
    file: roles/image_template/tasks/glance_image.yml
  - error: WRONG_HASH
    file: roles/image_template/examples/ovirt_image_template.yml
  - error: WRONG_HASH
    file: roles/image_template/README.md
  - error: WRONG_HASH
    file: roles/engine_setup/tests/engine-deploy.yml
  - error: WRONG_HASH
    file: roles/engine_setup/tests/engine-upgrade.yml
  - error: WRONG_HASH
    file: roles/engine_setup/examples/engine-deploy.yml
  - error: WRONG_HASH
    file: roles/engine_setup/examples/engine-upgrade.yml
  - error: WRONG_HASH
    file: roles/engine_setup/README.md
  - error: WRONG_HASH
    file: roles/remove_stale_lun/examples/remove_stale_lun.yml
  - error: WRONG_HASH
    file: roles/remove_stale_lun/README.md
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/tasks/create_storage_domain.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/tasks/alter_libvirt_default_net_configuration.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/tasks/bootstrap_local_vm/02_create_local_vm.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/tasks/pre_checks/002_validate_hostname_tasks.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/tasks/partial_execution.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/tasks/full_execution.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/tasks/create_target_vm/03_hosted_engine_final_tasks.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/tasks/create_target_vm/01_create_target_hosted_engine_vm.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/examples/hosted_engine_deploy_remotehost.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/examples/hosted_engine_deploy_localhost.yml
  - error: WRONG_HASH
    file: roles/hosted_engine_setup/README.md
  - error: WRONG_HASH
    file: roles/infra/tasks/create_infra.yml
  - error: WRONG_HASH
    file: roles/infra/tasks/remove_infra.yml
  - error: WRONG_HASH
    file: roles/infra/examples/ovirt_infra.yml
  - error: WRONG_HASH
    file: roles/infra/examples/ovirt_infra_destroy.yml
  - error: WRONG_HASH
    file: roles/infra/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/datacenter_cleanup/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/permissions/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/clusters/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/mac_pools/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/hosts/tasks/main.yml
  - error: WRONG_HASH
    file: roles/infra/roles/hosts/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/networks/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/datacenters/tasks/main.yml
  - error: WRONG_HASH
    file: roles/infra/roles/datacenters/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/aaa_jdbc/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/external_providers/README.md
  - error: WRONG_HASH
    file: roles/infra/roles/storages/README.md
  - error: WRONG_HASH
    file: changelogs/changelog.yaml
  - error: WRONG_HASH
    file: ovirt-ansible-collection.spec.in
  - error: WRONG_HASH
    file: plugins/inventory/ovirt.py
  - error: WRONG_HASH
    file: plugins/filter/convert_to_bytes.py
  - error: WRONG_HASH
    file: plugins/filter/ovirtvmipv6.yml
  - error: WRONG_HASH
    file: plugins/filter/convert_to_bytes.yml
  - error: WRONG_HASH
    file: plugins/filter/removesensitivevmdata.yml
  - error: WRONG_HASH
    file: plugins/filter/get_ovf_disk_size.yml
  - error: WRONG_HASH
    file: plugins/filter/ovirtvmipsv4.yml
  - error: WRONG_HASH
    file: plugins/filter/filtervalue.yml
  - error: WRONG_HASH
    file: plugins/filter/ovirtdiff.yml
  - error: WRONG_HASH
    file: plugins/filter/ovirtvmips.yml
  - error: WRONG_HASH
    file: plugins/filter/get_network_xml_to_dict.yml
  - error: WRONG_HASH
    file: plugins/filter/ovirtvmip.yml
  - error: WRONG_HASH
    file: plugins/filter/ovirtvmipsv6.yml
  - error: WRONG_HASH
    file: plugins/filter/ovirtvmipv4.yml
  - error: WRONG_HASH
    file: plugins/module_utils/ovirt.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_user_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_vm_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_disk.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_template_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_api_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_nic.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_snapshot.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_storage_vm_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_network_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_nic_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_mac_pool.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_instance_type.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_job.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_host_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_template.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_vnic_profile_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_storage_connection.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_vmpool_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_quota_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_vm.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_cluster_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_tag_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_permission.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_host_network.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_external_provider_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_event_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_disk_profile.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_storage_domain_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_tag.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_vm_os_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_quota.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_affinity_label.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_role.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_group_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_host_pm.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_external_provider.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_host_storage_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_snapshot_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_qos.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_datacenter.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_affinity_group.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_vnic_profile.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_permission_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_host.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_disk_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_cluster.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_datacenter_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_user.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_system_option_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_vmpool.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_network.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_affinity_label_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_storage_template_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_storage_domain.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_event.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_auth.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_scheduling_policy_info.py
  - error: WRONG_HASH
    file: plugins/modules/ovirt_group.py
  sensu.sensu_go:
  - error: WRONG_HASH
    file: docs/source/release_notes.rst
